### ISSUE TITLE
Inverted setting: Jump To behind

### ISSUE THREAD

**Issue by wilkerlucio** [eeemt/AceJump-Lite#2]
The "Jump To behind" setting seems to be reversed. When I have it on it's jumping *after* the character, while disabling makes it jump *behind*.

**Comment by wilkerlucio** [comment]
Maybe it's a language difference, I suggest it could be called "Jump to the left" or something like that, so it's not language direction dependent.

**Comment by EeeMt** [comment]
Thanks ! I think it's a good idea, I will change it.
